### ISSUE TITLE
Migrate Frontend Code to TypeScript

### ISSUE THREAD

**Issue by Gleethos** [Gleethos/Tribalism#1]
Ideally we should also migrate the code in the `backend-binder.js` file which does all
of the property binding and web-socket communication to view models...
But I would start at `App.js` and the `LoginView.js` which is not that complicated.

**Comment by Gleethos** [comment]
I also want to add that we should definitely tackle this before further developments like #2

**Comment by Gleethos** [comment]
I merged your pull request, but we are not fully done yet, the test I introduced in #20 is still in plain old JS.
We should migrate this as well.
Also I think the test is broken somehow after the TS migration. For some reason I can not run it anymore.
Can you maybe take a look at the test I wrote? It is my first react test and I would really appreciate a review? :)

**Comment by mischulz14** [comment]
I think I half fixed it in the last push to the main branch, can you try it out?

**Comment by Gleethos** [comment]
I just tried it but now I can no longer build the frontend. I think it is because the `magic.js` is now a TypeScript file and 
the runtime magic done in the file cannot be done in TS, but for some reason I am not getting a proper error message. 
I will try something else...

Is there a reason why you changed the magic file? :)

**Comment by Gleethos** [comment]
Also is there a reason why you committed this directly to master?
I have multiple compile errors and not sure how to fix them.
React screams at me that it does not understand `App.test.ts` because it 
does not understand the "HTML" part, I think we need `tsx` file for that.
Oh and I can no longer import `ReactTestUtils` for some strange reason.

One thing I might add is that for Unit Tests we do not really need type safety in my opinion.
I often like to rant about how unreliable scripting languages are, but to be completely honest
they are very useful for shallow and repetitive code where the type information is not actually
helping with finding bugs...
I mean, TS is not much more verbose than JS, so I don't mind, but just something I wanted to mention. :)

**Comment by mischulz14** [comment]
I changed the file names again to .js,, everything is working fine now!
